# Generated by Django 3.1.14 on 2022-04-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False, help_text='Select if record is archived', verbose_name='Is archived')),
                ('key', models.CharField(max_length=254)),
                ('value', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
