# Generated by Django 3.1.13 on 2021-08-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210211_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouping',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Phone number for grouping', max_length=256, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='personcontact',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for person', max_length=256, verbose_name='phone number'),
        ),
    ]
