# Generated by Django 3.1.13 on 2021-08-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210811_1857'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grouping',
            unique_together={('name', 'address')},
        ),
        migrations.RemoveField(
            model_name='grouping',
            name='code',
        ),
    ]
