# Generated by Django 3.1.13 on 2022-01-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_grouping_is_law_enforcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupingrelationship',
            old_name='as_of',
            new_name='at_least_since',
        ),
        migrations.RenameField(
            model_name='persongrouping',
            old_name='as_of',
            new_name='at_least_since',
        ),
        migrations.RenameField(
            model_name='personidentifier',
            old_name='as_of',
            new_name='at_least_since',
        ),
        migrations.RenameField(
            model_name='personpayment',
            old_name='as_of',
            new_name='at_least_since',
        ),
        migrations.RenameField(
            model_name='personrelationship',
            old_name='as_of',
            new_name='at_least_since',
        ),
        migrations.RenameField(
            model_name='persontitle',
            old_name='as_of',
            new_name='at_least_since',
        ),
    ]
