# Generated by Django 3.1.13 on 2022-05-09 13:57

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_trigram_similarity_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='search_full_text',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
