# Generated by Django 3.1.14 on 2022-06-23 15:56

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_trigram_similarity_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='search_full_text',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
