# Generated by Django 3.1.14 on 2022-06-30 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_person_search_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontitle',
            name='grouping',
            field=models.ForeignKey(blank=True, help_text='The group in which the title was held. Optional: use this when an officer holds two titles at the same time at different agencies.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persontitle_groupings', related_query_name='persontitle_grouping', to='core.grouping'),
        ),
    ]
