# Generated by Django 3.1.14 on 2022-07-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220722_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupingrelationship',
            name='ended_unknown_date',
            field=models.BooleanField(default=False, help_text="Select if you know that it has ceased but you don't know when.", verbose_name='ended at unknown date'),
        ),
        migrations.AddField(
            model_name='personidentifier',
            name='ended_unknown_date',
            field=models.BooleanField(default=False, help_text="Select if you know that it has ceased but you don't know when.", verbose_name='ended at unknown date'),
        ),
        migrations.AddField(
            model_name='personpayment',
            name='ended_unknown_date',
            field=models.BooleanField(default=False, help_text="Select if you know that it has ceased but you don't know when.", verbose_name='ended at unknown date'),
        ),
        migrations.AddField(
            model_name='personrelationship',
            name='ended_unknown_date',
            field=models.BooleanField(default=False, help_text="Select if you know that it has ceased but you don't know when.", verbose_name='ended at unknown date'),
        ),
        migrations.AddField(
            model_name='persontitle',
            name='ended_unknown_date',
            field=models.BooleanField(default=False, help_text="Select if you know that it has ceased but you don't know when.", verbose_name='ended at unknown date'),
        ),
        migrations.AlterField(
            model_name='persongrouping',
            name='ended_unknown_date',
            field=models.BooleanField(default=False, help_text="Select if you know that it has ceased but you don't know when.", verbose_name='ended at unknown date'),
        ),
    ]
