# Generated by Django 3.2.16 on 2023-01-03 14:20

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220728_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='search_full_text',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, help_text='System generated on record save. Do not edit the contents of this field.', null=True),
        ),
    ]
