# Generated by Django 3.1.3 on 2021-02-11 08:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_wizard', '0002_auto_20190306_2022'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_imported_from', models.CharField(help_text='External source, such as an earlier version of the FDP database, from which data was imported.', max_length=254, verbose_name='Source')),
                ('table_imported_from', models.CharField(blank=True, help_text='Table in external source from which data was imported.', max_length=254, verbose_name='Source table')),
                ('pk_imported_from', models.CharField(help_text='Primary key in external source uniquely identifying data that was imported.', max_length=254, verbose_name='Source primary key')),
                ('table_imported_to', models.CharField(help_text='Table in FDP to which data was imported.', max_length=254, verbose_name='FDP table')),
                ('pk_imported_to', models.IntegerField(help_text='Primary key in FDP uniquely identifying data that was imported.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='FDP primary key')),
                ('data_imported', models.JSONField(help_text='JSON representation of data that was imported.', verbose_name='Imported data')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Automatically added timestamp recording when import was performed.', verbose_name='timestamp')),
                ('notes', models.TextField(blank=True, help_text='Explanatory notes for the import.', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Bulk import log',
                'verbose_name_plural': 'Bulk import logs',
                'db_table': 'fdp_bulk_import',
                'ordering': ['timestamp', 'table_imported_to', 'pk_imported_to'],
            },
        ),
        migrations.CreateModel(
            name='FdpImportFile',
            fields=[
                ('filesource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sources.filesource')),
            ],
            options={
                'verbose_name': 'Import file',
                'verbose_name_plural': 'Import files',
                'db_table': 'fdp_import_file',
                'ordering': ['-date', 'name', 'file'],
            },
            bases=('sources.filesource',),
        ),
        migrations.CreateModel(
            name='FdpImportRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.OneToOneField(help_text='Instance of the Run model class that was defined in the Django Data Wizard package.', on_delete=django.db.models.deletion.CASCADE, related_name='fdp_import_run', related_query_name='fdp_import_run', to='data_wizard.run', verbose_name='Run')),
            ],
            options={
                'verbose_name': 'Import run',
                'verbose_name_plural': 'Import runs',
                'db_table': 'fdp_import_run',
                'ordering': ['run__serializer'],
            },
        ),
        migrations.CreateModel(
            name='FdpImportMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.OneToOneField(help_text='Instance of the Identifier model class that was defined in the Django Data Wizard package.', on_delete=django.db.models.deletion.CASCADE, related_name='fdp_import_mapping', related_query_name='fdp_import_mapping', to='data_wizard.identifier', verbose_name='Identifier')),
            ],
            options={
                'verbose_name': 'Import column mapping',
                'verbose_name_plural': 'Import column mappings',
                'db_table': 'fdp_import_mapping',
                'ordering': ['identifier__serializer', 'identifier__name'],
            },
        ),
        migrations.AddIndex(
            model_name='bulkimport',
            index=models.Index(fields=['table_imported_to', 'pk_imported_from', 'pk_imported_to'], name='fdp_bulk_im_table_i_874b70_idx'),
        ),
    ]
