# Generated by Django 3.1.13 on 2021-08-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encounterreason',
            options={'ordering': ['name'], 'verbose_name': 'encounter reason'},
        ),
    ]
