# Generated by Django 3.1.3 on 2021-02-11 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sourcing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False, help_text='Select if record is archived', verbose_name='Is archived')),
                ('name', models.CharField(help_text='Name of verification type', max_length=254, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'verification type',
                'db_table': 'fdp_verify_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VerifyPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False, help_text='Select if record is archived', verbose_name='Is archived')),
                ('description', models.TextField(blank=True, help_text='Verbose, user-friendly narrative', verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Automatically added timestamp for when the user verified the information', verbose_name='timestamp')),
                ('fdp_user', models.ForeignKey(help_text='User who verified the information', on_delete=django.db.models.deletion.CASCADE, related_name='verify_persons', related_query_name='verify_person', to=settings.AUTH_USER_MODEL, verbose_name='FDP user')),
                ('person', models.ForeignKey(help_text='Person whose information was verified by user', on_delete=django.db.models.deletion.CASCADE, related_name='verify_persons', related_query_name='verify_person', to='core.person', verbose_name='person')),
                ('type', models.ForeignKey(help_text='Category of verification performed for person', on_delete=django.db.models.deletion.CASCADE, related_name='verify_persons', related_query_name='verify_person', to='verifying.verifytype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'person verification',
                'db_table': 'fdp_verify_person',
                'ordering': ['timestamp', 'person', 'fdp_user'],
            },
        ),
        migrations.CreateModel(
            name='VerifyContentCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False, help_text='Select if record is archived', verbose_name='Is archived')),
                ('description', models.TextField(blank=True, help_text='Verbose, user-friendly narrative', verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Automatically added timestamp for when the user verified the information', verbose_name='timestamp')),
                ('content_case', models.ForeignKey(help_text='Content case which was verified by user', on_delete=django.db.models.deletion.CASCADE, related_name='verify_content_cases', related_query_name='verify_content_case', to='sourcing.contentcase', verbose_name='content case')),
                ('fdp_user', models.ForeignKey(help_text='User who verified the information', on_delete=django.db.models.deletion.CASCADE, related_name='verify_content_cases', related_query_name='verify_content_case', to=settings.AUTH_USER_MODEL, verbose_name='FDP user')),
                ('type', models.ForeignKey(help_text='Category of verification performed for content case', on_delete=django.db.models.deletion.CASCADE, related_name='verify_content_cases', related_query_name='verify_content_case', to='verifying.verifytype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'content case verification',
                'db_table': 'fdp_verify_content_case',
                'ordering': ['timestamp', 'content_case', 'fdp_user'],
            },
        ),
    ]
