"""
Django settings for Full Disclosure project.

Generated by 'django-admin startproject' using Django 3+.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import sys


#: To configure hosting in a local development environment, remove the comment from the below import statement.
#: This should not be used in a production environment.
# from .configuration.local.local_settings import *


#: To configure hosting in a Microsoft Azure environment, remove the comment from the below import statement.
# from .configuration.azure.azure_settings import *

#: To enforce user authentication only through the Azure Active Directory backend, remove the comment from the below
# import statement.
from .configuration.azure.azure_only_settings import *

# Send log messages to Azure Monitor
# Uncomment the below code and paste in
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    "handlers": {
        "console": {
            "level": "WARNING",
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
         },
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': '/tmp/fdp-app.log',
        },
    },
    'root': {
        'handlers': ["console", "file"],
        'level': 'WARNING',
    },
}

#: To allow files to be downloaded during a bulk import using the Django Data Wizard package, whitelist the
# starting portion of each URL. For example, to download files from either Air Tables or Google Drive:
# FDP_DJANGO_DATA_WIZARD_WHITELISTED_URLS = ['https://airtable.com/', 'https://drive.google.com/file/']


#: To customize the options that are listed on the federated login page, remove the comments from the below assignment.
# If no options are listed below, the federated login page will be skipped, and the user will be automatically
# redirected to the primary login page.
FEDERATED_LOGIN_OPTIONS = [
    {
        'label': 'Sign in with FDP',
        'url_pattern_name': 'two_factor:login',
        'url_pattern_args': [],
        'css': {'background-color': '#417690', 'color': '#FFF'},
        'css_hover': {'color': '#f5dd5d'}
    },
    {
        'label': 'Sign in with Azure Active Directory',
        'url_pattern_name': 'social:begin',
        'url_pattern_args': ['inheritable.models.AbstractConfiguration.azure_active_directory_provider'],
        'css': {'background-color': '#417690', 'color': '#FFF'},
        'css_hover': {'color': '#f5dd5d'}
    }
]
