# Generated by Django 3.1.3 on 2021-04-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Name of content. Use this for the article headline, report title or other user-friendly name.', max_length=254, verbose_name='name'),
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(_negated=True, link__iexact='')), fields=('link',), name='uq_content_link'),
        ),
    ]
