# Generated by Django 3.1.13 on 2021-08-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0002_auto_20210416_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentidentifier',
            name='identifier',
            field=models.CharField(help_text='Identifier number, such as the lawsuit number, IAB case number, or similar', max_length=254, verbose_name='identifier'),
        ),
    ]
