# Generated by Django 3.1.14 on 2022-04-07 23:49

from django.db import migrations, models
import django.db.models.deletion
import importer_narwhal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('completed', models.DateTimeField(null=True)),
                ('target_model_name', models.CharField(max_length=256)),
                ('number_of_rows', models.IntegerField(null=True)),
                ('errors_encountered', models.BooleanField(null=True)),
                ('submitted_file_name', models.CharField(max_length=1024)),
                ('import_sheet', models.FileField(upload_to='import-sheets/%Y/%m/%d/%H/%M/%S/', validators=[importer_narwhal.models.validate_import_sheet_extension, importer_narwhal.models.validate_import_sheet_file_size])),
            ],
        ),
        migrations.CreateModel(
            name='ImportedRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('action', models.CharField(max_length=128, null=True)),
                ('errors', models.TextField(null=True)),
                ('info', models.TextField(null=True)),
                ('imported_record_pk', models.CharField(max_length=128, null=True)),
                ('imported_record_name', models.CharField(max_length=1024, null=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_rows', to='importer_narwhal.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('error_message', models.TextField()),
                ('row_data', models.TextField()),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_rows', to='importer_narwhal.importbatch')),
            ],
        ),
    ]
