# Generated by Django 3.1.14 on 2022-03-15 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('target_model_name', models.CharField(max_length=256)),
                ('number_of_rows', models.IntegerField()),
                ('errors_encountered', models.BooleanField()),
                ('submitted_file_name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ImportedRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('imported_record_name', models.CharField(max_length=1024)),
                ('imported_record_pk', models.CharField(max_length=128)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_rows', to='importer_narwhal.importbatch')),
            ],
        ),
    ]
