# Generated by Django 3.1.14 on 2022-06-10 20:03

from django.db import migrations, models
import django.utils.timezone
import importer_narwhal.models


class Migration(migrations.Migration):

    dependencies = [
        ('importer_narwhal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importbatch',
            name='dry_run_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='dry_run_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='general_errors',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='import_sheet',
            field=models.FileField(help_text='Must be CSV format, encoded in UTF-8', upload_to='import-sheets/%Y/%m/%d/%H/%M/%S/', validators=[importer_narwhal.models.validate_import_sheet_extension, importer_narwhal.models.validate_import_sheet_file_size]),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='target_model_name',
            field=models.CharField(choices=[('Person', 'Person'), ('PersonContact', 'PersonContact'), ('PersonAlias', 'PersonAlias'), ('PersonPhoto', 'PersonPhoto'), ('PersonIdentifier', 'PersonIdentifier'), ('PersonTitle', 'PersonTitle'), ('PersonRelationship', 'PersonRelationship'), ('PersonPayment', 'PersonPayment'), ('Grouping', 'Grouping'), ('GroupingAlias', 'GroupingAlias'), ('GroupingRelationship', 'GroupingRelationship'), ('PersonGrouping', 'PersonGrouping'), ('Incident', 'Incident'), ('PersonIncident', 'PersonIncident'), ('GroupingIncident', 'GroupingIncident'), ('Attachment', 'Attachment'), ('Content', 'Content'), ('ContentIdentifier', 'ContentIdentifier'), ('ContentCase', 'ContentCase'), ('ContentPerson', 'ContentPerson'), ('ContentPersonAllegation', 'ContentPersonAllegation'), ('ContentPersonPenalty', 'ContentPersonPenalty'), ('State', 'State'), ('County', 'County'), ('Location', 'Location'), ('Court', 'Court'), ('Trait', 'Trait'), ('TraitType', 'TraitType')], help_text='Select the data model that you would like to import to. Read more about appropriate mappings \n         on the Mappings page.', max_length=256),
        ),
    ]
