# Generated by Django 3.1.14 on 2022-04-09 01:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('importer_narwhal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
