# Generated by Django 3.1.14 on 2022-03-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer_narwhal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedrow',
            name='action',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='importedrow',
            name='errors',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='importedrow',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='importedrow',
            name='imported_record_name',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='importedrow',
            name='imported_record_pk',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
