# Generated by Django 3.2.15 on 2022-12-02 21:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer_narwhal', '0002_auto_20220610_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('models_to_export', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), help_text='Choose which data models to include in the export. Allows multiple.', size=None)),
                ('export_file', models.FileField(blank=True, null=True, upload_to='data-exports/')),
            ],
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='target_model_name',
            field=models.CharField(choices=[('Person', 'Person'), ('PersonContact', 'PersonContact'), ('PersonAlias', 'PersonAlias'), ('PersonPhoto', 'PersonPhoto'), ('PersonIdentifier', 'PersonIdentifier'), ('PersonTitle', 'PersonTitle'), ('PersonRelationship', 'PersonRelationship'), ('PersonPayment', 'PersonPayment'), ('Grouping', 'Grouping'), ('GroupingAlias', 'GroupingAlias'), ('GroupingRelationship', 'GroupingRelationship'), ('PersonGrouping', 'PersonGrouping'), ('Incident', 'Incident'), ('PersonIncident', 'PersonIncident'), ('GroupingIncident', 'GroupingIncident'), ('Attachment', 'Attachment'), ('Allegation', 'Allegation'), ('AllegationOutcome', 'AllegationOutcome'), ('Content', 'Content'), ('ContentIdentifier', 'ContentIdentifier'), ('ContentCase', 'ContentCase'), ('ContentCaseOutcome', 'ContentCaseOutcome'), ('ContentIdentifierType', 'ContentIdentifierType'), ('ContentPerson', 'ContentPerson'), ('ContentPersonAllegation', 'ContentPersonAllegation'), ('ContentPersonPenalty', 'ContentPersonPenalty'), ('EncounterReason', 'EncounterReason'), ('GroupingRelationshipType', 'GroupingRelationshipType'), ('IncidentLocationType', 'IncidentLocationType'), ('IncidentTag', 'IncidentTag'), ('PersonIncidentTag', 'PersonIncidentTag'), ('State', 'State'), ('County', 'County'), ('Location', 'Location'), ('Court', 'Court'), ('Trait', 'Trait'), ('TraitType', 'TraitType')], help_text='Select the data model that you would like to import to. Read more about appropriate mappings \n         on the Mappings page.', max_length=256),
        ),
    ]
