# Generated by Django 3.1.13 on 2022-06-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer_narwhal', '0002_auto_20220409_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='dry_run_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='dry_run_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
