# Generated by Django 3.1.14 on 2022-03-17 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importer_narwhal', '0002_auto_20220317_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('error_message', models.TextField()),
                ('row_data', models.TextField()),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_rows', to='importer_narwhal.importbatch')),
            ],
        ),
    ]
