# Generated by Django 3.1.14 on 2022-03-18 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('importer_narwhal', '0003_errorrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importbatch',
            name='start_time',
        ),
        migrations.AddField(
            model_name='importbatch',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='errors_encountered',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='number_of_rows',
            field=models.IntegerField(null=True),
        ),
    ]
