# Generated by Django 3.1.14 on 2022-03-18 12:54

from django.db import migrations, models
import importer_narwhal.models


class Migration(migrations.Migration):

    dependencies = [
        ('importer_narwhal', '0004_auto_20220318_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='import_sheet',
            field=models.FileField(default='', upload_to='import-sheets/%Y/%m/%d/%H/%M/%S/', validators=[importer_narwhal.models.validate_import_sheet_extension, importer_narwhal.models.validate_import_sheet_file_size]),
            preserve_default=False,
        ),
    ]
