# Generated by Django 3.1.13 on 2021-09-21 21:32

from django.db import migrations, models
import inheritable.models


class Migration(migrations.Migration):

    dependencies = [
        ('fdpuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='End-user license agreement file. Should be less than 100MB.', max_length=254, unique=True, upload_to='eula/%Y/%m/%d/%H/%M/%S/', validators=[inheritable.models.AbstractFileValidator.validate_eula_file_size, inheritable.models.AbstractFileValidator.validate_eula_file_extension], verbose_name='File')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Automatically added timestamp for when EULA was uploaded', verbose_name='timestamp')),
            ],
            options={
                'verbose_name': 'EULA',
                'verbose_name_plural': 'EULAs',
                'db_table': 'fdp_eula',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='fdpuser',
            name='agreed_to_eula',
            field=models.DateTimeField(blank=True, help_text='Date and time that the user agreed to a EULA. None if user has not agreed to a EULA.', null=True, verbose_name='EULA agreement'),
        ),
    ]
